version: '3.8'
services:
  next:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hotel
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
volumes:
  mongo_data:
